version: '{build}'

environment:
  mssql_jdbc_test_connection_properties: jdbc:sqlserver://localhost:1433;instanceName=SQL2016;databaseName=master;username=sa;password=Password12!;
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0 

services:
  - mssql2016

build_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pbuild41
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pbuild42
test_script:
  - mvn test -B -Pbuild41
  - mvn test -B -Pbuild42